airwallex/airwallex-payment-ios

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Core/Sources/AWXApplePayOptions.h, Airwallex/Core/Sources/AWXApplePayOptions.m, Airwallex/Core/Sources/AWXConstants.h, Airwallex/Core/Sources/AWXConstants.m, Airwallex/Core/Sources/AWXDefaultProvider.h, Airwallex/Core/Sources/AWXDefaultProvider.m, Airwallex/Core/Sources/AWXPaymentMethod.h, Airwallex/Core/Sources/AWXPaymentMethodListViewController.m, Airwallex/Core/Sources/AWXSession.h, Airwallex/Core/Sources/AWXUtils.m, Airwallex/Core/Sources/Core.h, Airwallex/CoreTests/AWXApplePayOptionsTest.m, Airwallex/CoreTests/AWXConstantsTest.m, Airwallex/CoreTests/AWXDefaultProviderTest.m
This PR
- exposes a new `ApplePayOptions` class on the `AWXSession` for merchants to specify the necessary parameters in order for Apple Pay to work.
- added a new static method `canHandleSession` to `AWXDefaultProvider` so that subclasses can optionally check if a particular session is supported. This will help avoid showing Apple Pay button in the payment list if Apple Pay is not available on this device. The actual implementation will be introduced in the next PR.
The options is marked as optional, meaning that if the merchant doesn't support Apple Pay or the merchant hasn't integrated the upcoming Apple Pay module, then there's no need to specify the options.
The properties and the default values of the options should match the ones defined in the web implementation. …
=> [MOB-719] Apple Pay options

Airwallex.podspec, Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Airwallex.xcodeproj/xcshareddata/xcschemes/ApplePay.xcscheme, Airwallex/Airwallex.xctestplan, Airwallex/ApplePay/AWXApplePayProvider.h, Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/ApplePay/ApplePay.h, Airwallex/ApplePayTests/AWXApplePayProviderTest.m, Airwallex/Core/Sources/AWXConstants.m, Airwallex/CoreTests/AWXConstantsTest.m, Examples/Examples.xcodeproj/project.pbxproj, Examples/Examples/Cart/CartViewController.m, Examples/Examples/Examples.entitlements, Podfile, Podfile.lock
This PR:
- introduced `AWXApplePayProvider` to handle Apple Pay payment method. 
- `AWXApplePayProvider` overrides `canHandleSession` to check:
1.  whether a merchant identifier is configured.
2. whether the session is a one off session. For MVP, Apple Pay only supports one off payment.
3. whether the device has a card in Wallet that can support visa, Mastercard, UnionPay or maestro as well as support the merchant capabilities defined in the `AWXApplePayOptions`.
- Added a new subspec in Cocoapods. But it's excluded from the default modules.
- Added Apple Pay capability to the Examples target and used our sample merchant ID (merchant.com.airwallex.paymentacceptance) for testing and demoing purpose.
=> [MOB-719] feat: toggle apple pay button visibility 

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/Core/Sources/Internal/AWXConstants+Internal.h, Airwallex/Core/Sources/Internal/AWXConstants+Internal.m, Airwallex/Core/Sources/Internal/AWXPaymentMethodListViewController.m, Airwallex/Core/Sources/Internal/AWXSession+Internal.h, Airwallex/Core/Sources/Internal/AWXSession+Internal.m, Airwallex/CoreTests/AWXConstantsInternalTest.m, Airwallex/CoreTests/AWXSessionInternalTest.m
This PR filtered out unsupported payment method types as a short term solution.
In long term, ideally, the payment intent API should handle this for us.
=> [MOB-758] fix: filtered out unsupported payment methods when presenting the payment method selection sheet

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/ApplePay/Internal/AWXOneOffSession+Request.m, Airwallex/ApplePay/Internal/AWXPaymentIntent+Summary.h, Airwallex/ApplePay/Internal/AWXPaymentIntent+Summary.m, Airwallex/ApplePay/Internal/AWXPlaceDetails+PKContact.h, Airwallex/ApplePay/Internal/AWXPlaceDetails+PKContact.m, Airwallex/ApplePay/Internal/PKContact+Request.h, Airwallex/ApplePay/Internal/PKContact+Request.m, Airwallex/ApplePay/Internal/PKPaymentToken+Request.h, Airwallex/ApplePay/Internal/PKPaymentToken+Request.m, Airwallex/ApplePayTests/AWXApplePayProviderTest.m, Airwallex/ApplePayTests/AWXOneOffSessionRequestTest.m, Airwallex/ApplePayTests/AWXPaymentIntentSummaryTest.m, Airwallex/ApplePayTests/AWXPlaceDetailsPKContactTest.m, Airwallex/ApplePayTests/PKContactRequestTest.m, Airwallex/ApplePayTests/PKPaymentTokenRequestTest.m, Airwallex/Core/Sources/AWXApplePayOptions.h, Airwallex/Core/Sources/AWXApplePayOptions.m, Airwallex/CoreTests/AWXApplePayOptionsTest.m, Examples/Examples/Cart/CartViewController.m
This PR 
- added a new field on `AWXApplePayOptions` class to allow merchants to provide additional payment summary items  to be shown to the customers.
- removed shipping related options from `AWXApplePayOptions`. We don't support editing shipping information on the Apple Pay prompt.
- handled billing edit and sent billing information to the API when confirming the payment intent. See attached demo.
https://user-images.githubusercontent.com/73088020/163294994-bcdae274-5497-4fd5-ab0a-b59d83d1113e.mov
=> fix: fixed a few issues with the SDK

Airwallex/Core/Sources/Internal/AWXPaymentMethodRequest.h, Airwallex/Core/Sources/Internal/AWXPaymentMethodRequest.m, Airwallex/CoreTests/API/AWXPaymentMethodFunctionalTest.m
This PR added a flow parameter to the queries when requesting payment method types for the payment method sheet. This will help filter out Apple Pay when it's only configured for web domains.
=> fix: added a flow parameter when requesting payment method types

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Card/AWXCardProvider.h, Airwallex/Card/AWXCardProvider.m, Airwallex/Card/Internal/AWXCardViewController.m, Airwallex/Core/Sources/AWXConstants.h, Airwallex/Core/Sources/AWXConstants.m, Airwallex/Core/Sources/AWXDefaultProvider.h, Airwallex/Core/Sources/AWXDefaultProvider.m, Airwallex/Core/Sources/Internal/AWXPaymentConsentRequest.m, Airwallex/Core/Sources/Internal/AWXPaymentMethodListViewController.m, Airwallex/CoreTests/API/AWXPaymentConsentRequestTest.m, Airwallex/CoreTests/AWXConstantsTest.m, Airwallex/CoreTests/AWXDefaultProviderTest.m
This pr enables save card feature in one-off payment by:
- Display toggle in card payment UI when having customer ID
- Create payment consent using the card payment method and then confirm payment intent
- Removes duplicate cards based on their `fingerprint`
Before change:
After change:
=> [MOB-1009] Save card in one-off payment session

Examples/Examples/Examples.entitlements
This PR enabled push notification for the Example app. 
We were getting email warnings saying this:
The Example app doesn't even have push notification enabled in either the App ID configuration or the entitlement file. According to the thread https://developer.apple.com/forums/thread/15011, it could still be a false positive.
Regardless, we enable the push and silence the warning.
=> chore: silence push notification warning

.github/workflows/create-release.yml, .github/workflows/tests.yml
There is a limitation which wasn't picked up during my tests:
GitHub won't allow CI pipelines to push commits directly into a protected branch. The feature branch I had didn't have the protected rule set up so this was missed. The issue was then discovered after the PR was merged and the action failed because of this. https://github.com/airwallex/airwallex-payment-ios/actions/runs/3202752812/jobs/5232062599
More on the issue can be found at https://github.com/community/community/discussions/13836.
This PR workarounds the issue by using a special PAT generated under the mobile service account. The service account has admin permissions to bypass the limitation.
=> [MOB-1048] fix: workaround an issue where it's not allowed to push directly into protected branches

.github/workflows/create-release.yml, .github/workflows/tests.yml
There are two workflows for automatic releasing the SDK:
- versioning bump workflow: the workflow used to figure out the next version, update the files that require version, commit the changes, tag the commit and then create a GitHub release.
- deploy workflow: whenever a tag is created, this workflow will download the tagged commit and make a deployment.
We rely on the first workflow to create a tag which will trigger the second workflow. However, it turns out the tagging created by GitHub bots [won't be able to trigger another workflow](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow).
This PR workarounds that, just like the previous PR #38, by using the service account's PAT.
=> [MOB-1048] chore: used service account PAT for tagging in order to trigger another workflow

Airwallex/Core/Sources/AWXSession.h, Airwallex/Core/Sources/AWXSession.m, Airwallex/CoreTests/AWXDefaultProviderTest.m, Airwallex/CoreTests/Models/AWXSessionTest.m, Examples/Examples/AirwallexExamplesKeys.m
This pr
- sets `autoCapture` of one off and recurring with intent session to `true` by default so that the payment will be automatically captured without customer's extra config.
- also sets the demo app's `autoCapture` in Settings as turned on by default.
=> [MOB-1113] Set autoCapture to true by default

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Core/Sources/Internal/AWXPaymentMethodListViewController.m, Airwallex/Redirect/AWXSchemaProvider.m, Airwallex/RedirectTests/AWXSchemaProviderTests.m
This pr supports KCP by:
- Skip bank selection when bank list is empty from response and show user info input field
=> [MOB-1594] Show schema field when bank list is empty

Airwallex/Card/Internal/AWXCardViewController.m, Airwallex/Card/Internal/AWXCardViewModel.h, Airwallex/Card/Internal/AWXCardViewModel.m, Airwallex/CardTests/AWXCardViewModelTests.m
To display 'Confirm' instead of 'Pay' as button title in recurring session.
=> [MOB-1832] Change CTA title in recurring session

Airwallex/ApplePay/AWXApplePayProvider.h, Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/ApplePay/Internal/AWXOneOffSession+Request.m, Airwallex/ApplePayTests/AWXApplePayProviderTest.m, Airwallex/ApplePayTests/AWXOneOffSessionRequestTest.m, Airwallex/CardTests/AWXCardProviderTests.m, Airwallex/CoreTests/AWXDefaultProviderTest.m, Airwallex/CoreTests/AWXNextActionHandlerTest.m, Airwallex/CoreTests/AWXProviderDelegateEmpty.m, Examples/Examples/AirwallexExamplesKeys.h, Examples/Examples/AirwallexExamplesKeys.m, Examples/Examples/Cart/CartViewController.m, Examples/Examples/Cart/OptionsViewController.m, Examples/Examples/Demo/WebViewController.m, Examples/Examples/Resources/Base.lproj/Main.storyboard, README.md
- Exposed `makePayment` api in `AWXApplePayProvider` to initiate apple pay flow directly.
- Refactored implementation of AWXApplePayProvider for early check and return in case of error and also to return payment cancel status if user cancels the payment in case of payment flow initiated via `makePayment`
- Added an option in the settings screen to initiate apple pay directly when turned on instead of presenting the payment method list screen.
=> [Mob-2055] Allow apple pay low level api Integration

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/Card/AWX3DSActionProvider.m, Airwallex/Card/AWXCardProvider.m, Airwallex/Card/AWXDccActionProvider.m, Airwallex/Card/Internal/AWXCardViewController.m, Airwallex/CardTests/AWXCardProviderTests.m, Airwallex/Core/Sources/AWXAPIClient.h, Airwallex/Core/Sources/AWXAPIClient.m, Airwallex/Core/Sources/AWXDefaultProvider.m, Airwallex/Core/Sources/Internal/AWXPaymentMethodListViewController.m, Airwallex/Core/Sources/Internal/AWXPaymentViewController.m, Airwallex/Core/Sources/Internal/Extensions/NSObject+Logging.h, Airwallex/Core/Sources/Internal/Extensions/NSObject+Logging.m, Airwallex/CoreTests/AWXAPIClientTest.m, Airwallex/Redirect/AWXRedirectActionProvider.m, Airwallex/Redirect/AWXSchemaProvider.m, Airwallex/RedirectTests/AWXSchemaProviderTests.m, Airwallex/WeChatPay/AWXWeChatPayActionProvider.m, Examples/Examples/Cart/CartViewController.m, sonar-project.properties
Add local logs for AWXProviderDelegate.
add [Airwallex enableLocalLogFile] to enable storing logs into local file (called "AirwallexSDK.log")
This will automatically store the log when we call [NSObject log:] when true.
The log file will be cleared if last clearance time is 7 days ago.
=> [APAM-24] [APAM-23]collect local logs in local file system if needed

Airwallex/Redirect/AWXRedirectActionProvider.m, Airwallex/RedirectTests/AWXRedirectActionProviderTests.m
This pr fixes the issue that app redirection error is not handled:
- Return In progress status when open application succeeds
- Return fail status with error info when fails
=> [APAM-41] Fix open application error not returned

Airwallex/ApplePay/AWXApplePayProvider.m, Airwallex/Card/AWXCardProvider.m, Airwallex/Security/AWXSecurityService.m
- Pass risk session ID regardless of signifyd session ID
- Bring forward initialisation of signifyd to the moment when card/applepay provider is initiated
=> [APAM-46] Risk improve

Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Card/AWXCardViewController.m, Airwallex/Card/AWXCardViewModel.h, Airwallex/Card/AWXCardViewModel.m, Airwallex/CardTests/AWXCardViewModelTests.m, Airwallex/Core/Sources/AWXAPIClient.m, Airwallex/Core/Sources/AWXCard.m, Airwallex/Core/Sources/AWXCardValidator.h, Airwallex/Core/Sources/AWXCardValidator.m, Airwallex/Core/Sources/AWXFloatingCardTextField.h, Airwallex/Core/Sources/AWXFloatingCvcTextField.h, Airwallex/Core/Sources/AWXFloatingCvcTextField.m, Airwallex/Core/Sources/AWXWidgets.h, Airwallex/Core/Sources/AWXWidgets.m, Airwallex/CoreTests/Models/AWXCardTest.m, Airwallex/CoreTests/Tools/AWXCardValidatorTest.m, Examples/Examples/Cart/CartViewController.m
This improves card cvc validation by:
- Limit input length according to card scheme
- Show different validation message
- Fix layout that cvc error message is truncated
=> [APAM-55] Card cvc validation

Airwallex.podspec, Airwallex/Airwallex.xcodeproj/project.pbxproj, Airwallex/Card/AWXCardProvider+PaymentConsent.swift, Airwallex/CardTests/AWXCardProviderTests.m, Airwallex/Core/Sources/AWXConstants.h, Airwallex/Core/Sources/AWXConstants.m, Airwallex/Core/Sources/AWXDefaultProvider.h, Airwallex/Core/Sources/AWXDefaultProvider.m, Airwallex/Core/Sources/Internal/AWXPaymentMethodRequest.m, Airwallex/CoreTests/AWXDefaultProviderTest.m, Airwallex/Redirect/AWXRedirectActionProvider+PaymentIntent.swift, Airwallex/Redirect/AWXRedirectActionProvider.m, Airwallex/Redirect/AWXSchemaProvider.m, Airwallex/RedirectTests/AWXRedirectActionProviderTests.m, Examples/Examples/AirwallexExamplesKeys.h, Examples/Examples/AirwallexExamplesKeys.m, Examples/Examples/Cart/CartViewController.swift, Examples/Examples/Cart/OptionsViewController.m, Examples/Examples/Resources/Base.lproj/Main.storyboard, Podfile.lock, README.md, README_zh_CN.md
This provides low-level API `confirmPaymentIntentWithPaymentMethodName:additionalInfo:flow:` that can confirm a payment intent with LPM redirect payment.
=> [APAM-57] Add redirect pay low-level api

Airwallex/Card/AWXCardViewController.m, Airwallex/Card/AWXCardViewModel.h, Airwallex/Card/AWXCardViewModel.m, Airwallex/CardTests/AWXCardViewModelTests.m, Airwallex/Core/Sources/AWXSession.h, Airwallex/Core/Sources/AWXSession.m, Examples/Examples/Cart/CartViewController.swift
default value of card switcher can be configured by this property in `AWXOneOffSession `
```
/// Indicates whether card saving is enabled by default for card payments. Defaults to NO.
@property (nonatomic, assign) BOOL isCardSavingEnabledByDefault;
```
=> APAM-142 make save card switcher configurable

Airwallex/AirwallexPaymentSheet/Sources/PaymentSheet/View/InputFields/InfoCollectorTextFieldViewModel.swift
Clear button tap action is not handled correctly. When user click clear button, input validation status and data on InfoCollectorTextFieldViewModel is not updated because the text change will not trigger callback of `textField(_:shouldChangeCharactersIn:replacementString:)`
=> fix: APAM-196 handling clear button action
